version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySQL!234
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: my-php-myadmin
    ports:
      - "8085:80"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - mysql_network

volumes:
  db:
    driver: local

networks:
  mysql_network:
    driver: bridge
